# Generated by Django 5.2.9 on 2026-01-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='de', max_length=2, verbose_name='Document Language')),
                ('project_number', models.CharField(max_length=50, verbose_name='Project Number')),
                ('heading', models.CharField(max_length=200, verbose_name='Heading')),
                ('project_title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('client_info', models.TextField(verbose_name='Client Details')),
                ('financier', models.CharField(blank=True, max_length=200, verbose_name='Financier')),
                ('object_name', models.CharField(max_length=200, verbose_name='Object Name')),
                ('performance_short', models.TextField(verbose_name='Performance (Bullets)')),
                ('task_description', models.TextField(verbose_name='Task Description')),
                ('performance_description', models.TextField(verbose_name='Performance Description')),
                ('date_from', models.DateField(verbose_name='Date From')),
                ('date_until', models.DateField(blank=True, null=True, verbose_name='Date Until')),
                ('processing_periods_months', models.IntegerField(blank=True, null=True, verbose_name='Duration (Months)')),
                ('total_fee', models.CharField(blank=True, max_length=100, verbose_name='Total Fee')),
                ('fee_kocks', models.CharField(blank=True, max_length=100, verbose_name='Kocks Fee')),
                ('fee_planning', models.CharField(blank=True, max_length=100, verbose_name='Fee Planning')),
                ('fee_construction', models.CharField(blank=True, max_length=100, verbose_name='Fee Construction')),
                ('tech_value_header', models.TextField(blank=True, verbose_name='Technical Headings')),
                ('tech_value_text', models.TextField(blank=True, verbose_name='Technical Values')),
                ('staff_total', models.IntegerField(blank=True, null=True, verbose_name='Total Staff')),
                ('staff_kocks', models.IntegerField(blank=True, null=True, verbose_name='Kocks Staff')),
                ('senior_staff_names', models.TextField(blank=True, verbose_name='Senior Staff Names')),
                ('man_months_total', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Total Man-Months')),
                ('man_months_kocks', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Kocks Man-Months')),
                ('partner_companies', models.TextField(blank=True, verbose_name='Partner Companies')),
                ('captions', models.TextField(blank=True, verbose_name='Photo Captions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
                ('content_type', models.CharField(max_length=50)),
                ('folder_name', models.CharField(editable=False, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projectsheets.projectsheet')),
            ],
        ),
    ]
